name: vector_tile_it
description: "A vector tile layer for FlutterMap"
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.2.0
  logging: ^1.2.0
  p_limit: ^1.0.3
  path_provider: ^2.1.2
  vector_tile_renderer:
    path: vendor/vector_tile_renderer
  dart_ui_isolate: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  test: ^1.24.9

flutter:

